tunnel: b43522fe-47f3-42f0-b4ea-6daf81287ef2

credentials-file: /etc/cloudflared/b43522fe-47f3-42f0-b4ea-6daf81287ef2.json

ingress:
  - hostname: app.ccr.id.lv
    service: http://frontend:5173
  - service: http_status:404