name: sync-local

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes into local repo
        run: |
          cd C:\Users\flawy\Documents\project-github\Minigames_site
          git pull origin main
